### PR TITLE
Add timestamps to `post_votes` table

### PR DESCRIPTION
**Pull request by iPurpl3x**
**Changes proposed in this pull request:**
Added `created_at` to `post_votes` table.
 This is analog to https://github.com/flarum/core/issues/2840 & https://github.com/flarum/likes/pull/28

**Confirmed**

- [x] Backend changes: tests are green (run `composer test`).

### CODE REVIEW

**Comment by imorland** [comment]
Thanks for this. I'd be inclined to also add `updated_at` to this table as well, as users may have the permission to alter their vote after first casting it

**Comment by iPurpl3x** [comment]
Ah yes that makes sense @imorland. I'm on it.

**Review by imorland — CHANGES_REQUESTED** [review]
Thanks for putting this together, I think adding these timestamps is very useful.

However, I'm not sure this approach will give the expected results. My observations:
- Upon running the migration, all existing rows are populated with the current timestamp, in both `created_at` and `updated_at`. My expectation would be that existing rows would remain `null` after the migration has been run.
- `updated_at` is not actually updated on a vote change

**Comment by iPurpl3x** [comment]
Sure that all makes sense @imorland, I'll address those issues.

Note:
Now I see that in https://github.com/flarum/likes/pull/28 we didn't take care of the fact that the timestamps get populated with the current timestamp and not NULL...

**Review by imorland — APPROVED** [review]

**Pull request merged**
